language: android

jdk: oraclejdk8

sudo: false

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-26

  #Extras
  - extra-android-m2repository
  - extra-google-m2repository  # Removed duplicated component

script:
  - ./gradlew test
  - ./gradlew clean createDebugCoverageReport
